item:
  empty-hand-warning: "ยง6You aren't holding an item."
  keywords:
    - "[i]"
    - "[item]"
inventory:
  expired-warning: "ยง6The inventory has either expired or is invalid."
  cache-duration-minutes: 5
  keywords:
    - "[inv]"
    - "[inventory]"
